# Employees for specs. Codes are set explicitly here; in the app they are
# generated by Employees::CreateService.
FactoryBot.define do
  factory :employee do
    sequence(:employee_code) { |n| format("EMP%06d", n) }
    first_name { "Asha" }
    last_name { "Verma" }
    sequence(:email) { |n| "employee#{n}@acme.test" }
    country_code { "IN" }
    department
    designation { "Software Engineer" }
    joining_date { Date.new(2024, 1, 15) }
    employment_status { "active" }

    trait :terminated do
      employment_status { "terminated" }
      exit_date { Date.new(2025, 6, 30) }
    end

    trait :deleted do
      deleted_at { Time.current }
    end
  end
end
